apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-deployment-listing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view   # 'view' ClusterRole allows read-only access to many resources, including deployments
subjects:
- kind: User
  name: sooter.touchstone@gmail.com
